"""The whole experiment: three baselines, the rules-only ablation, and the agent.

    python -m scripts.run_report_card                 (uses the committed cache)
    python -m scripts.run_report_card --live          (calls the model for anything
                                                       not already cached)
    python -m scripts.run_report_card --model gemini-2.5-flash-lite

Writes `results/report_card.json` and `results/RESULTS.md`, and prints both the
comparison table and the ablation verdict.

Reproducibility: with the committed `data/thinker_cache.json` this runs offline
and produces exactly the published numbers, on any machine, with no API key. That
is submission checklist item 2, and it is why the cache is in the repository
rather than in .gitignore.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from app import cohort, report, runner, thinker
from app.config import PROJECT_ROOT
from app.db import SessionLocal, init_db
from app.ledger import verify_chain
from app.policies import get

BASELINE_NAMES = ["do_nothing", "blast_everyone", "blast_everyone_gated",
                  "retry_everything", "rules_only"]
RESULTS_DIR = PROJECT_ROOT / "results"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run the full Recoup report card.")
    parser.add_argument("--live", action="store_true",
                        help="allow real model calls for cases not in the cache")
    parser.add_argument("--model", default=None)
    parser.add_argument("--seed", type=int, default=cohort.SEED)
    parser.add_argument("--no-audit", action="store_true")
    parser.add_argument("--out", default=str(RESULTS_DIR))
    args = parser.parse_args(argv)

    init_db()
    agent_policy, brain = thinker.build_policy(model=args.model, offline=not args.live)

    with SessionLocal() as session:
        rows = runner.load_cohort(session)

        # Warm the cache first, concurrently. The scored run itself is strictly
        # sequential -- the Guard's frequency rules only mean something in a
        # fixed order -- so the network round trips are got out of the way here.
        from app import watcher
        signals = watcher.scan([case for case, _ in rows], as_of=cohort.AS_OF)
        warm = brain.prewarm(signals)
        if warm.get("requested"):
            print(f"thinker  planned {warm['requested']} new cases "
                  f"({warm.get('errors', 0)} errors), {warm['cached_already']} already cached\n")
        elif brain.offline:
            print(f"thinker  offline, using {len(brain.cache)} cached plans\n")

        policies = [get(name) for name in BASELINE_NAMES] + [agent_policy]
        results = runner.run_all(
            session, policies, seed=args.seed, audit=not args.no_audit,
        )

        chain = verify_chain(session)

    brain.close()

    card = report.build(results, rows)
    card["meta"] = {
        "seed": args.seed,
        "cohort_fingerprint": cohort.fingerprint(cohort.build_cohort(seed=args.seed)),
        "as_of": cohort.AS_OF.isoformat(),
        "model": brain.model,
        "offline": brain.offline,
        "llm_live_calls": brain.calls,
        "llm_cache_hits": brain.cache_hits,
        "llm_fallbacks": brain.fallbacks,
        "llm_cost_paise": brain.cost_paise,
        "ledger_entries": chain.entries,
        "ledger_chain_intact": chain.ok,
    }

    print(report.render(card))
    print(report.render_rule_breakdown(card))
    print(report.render_ablation(card))

    print()
    print(f"  cohort fingerprint  {card['meta']['cohort_fingerprint']}")
    print(f"  ledger              {chain.entries} entries, chain "
          f"{'intact' if chain.ok else 'BROKEN: ' + chain.detail}")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "report_card.json").write_text(
        json.dumps(card, indent=2), encoding="utf-8"
    )
    (out_dir / "RESULTS.md").write_text(_markdown(card), encoding="utf-8")
    print(f"\n  written             {out_dir / 'report_card.json'}")
    print(f"                      {out_dir / 'RESULTS.md'}")
    return 0


def _markdown(card: dict) -> str:
    meta = card["meta"]
    return f"""# Recoup - results

Generated by `python -m scripts.run_report_card`. Every number below is
reproducible: same seed, same cohort fingerprint, same committed model cache.

- cohort seed: `{meta['seed']}`
- cohort fingerprint: `{meta['cohort_fingerprint']}`
- as-of: `{meta['as_of']}`
- planner: `{meta['model']}` ({'cache only' if meta['offline'] else 'live'})
- audit ledger: {meta['ledger_entries']} entries, chain {'intact' if meta['ledger_chain_intact'] else 'BROKEN'}

## The comparison

{report.to_markdown(card)}

## How to read it

**caused** is the only number worth comparing. It is the money that arrived
*because of* the policy, with customers who would have paid unprompted removed.
**collected** is what a normal recovery dashboard would show you, and the gap
between the two columns is the reason this project exists: `do_nothing` collects
{report.rupees(card['cohort']['self_paying_paise'])} while causing nothing at all.

**violations** counts guard rules the policy broke. The baselines run ungated,
because a merchant blasting their customer list does not have a compliance layer
- that is what makes it a bad idea. `blast_everyone_gated` is the same strategy
with Recoup's Guard switched on, so the effect of *targeting* can be separated
from the effect of *compliance*.

## Ablation

```
{report.render_ablation(card)}
```
"""


if __name__ == "__main__":
    sys.exit(main())
